import Head from 'next/head';
import NavigationBar from '@/components/common/NavigationBar';
import LoginAfterNavigationBar from '@/components/common/NavigationBar/LoginAfterNavigationBar';
import ArtistNavigationBar from '@/components/common/NavigationBar/ArtistNavigationBar';

import MainBanner from '@/components/main/MainBanner';
import ArtContent from '@/components/main/ArtContent';
import api from '@/services/TokenService';

const Home = () => {
  const token = api.getToken();
  const role = api.getRole();

  return (
    <div>
      <Head>
        <title>Objet</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {token == null ? (
        <NavigationBar />
      ) : role === 'USER' ? (
        <LoginAfterNavigationBar />
      ) : (
        <ArtistNavigationBar />
      )}
      <MainBanner />
      <ArtContent />
    </div>
  );
};

export default Home;
