import Head from 'next/head';
import NavigationBar from '@/components/common/NavigationBar';
import MainBanner from '@/components/main/MainBanner';
import ArtContent from '@/components/main/ArtContent/ArtContent';

const Home = () => (
  <>
    <Head>
      <title>Objet</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <NavigationBar />
    <MainBanner />
    <ArtContent />
  </>
);

export default Home;
