import Head from 'next/head';
import NavigationBar from '@/components/common/NavigationBar';
import MainBanner from '@/components/main/MainBanner';
import ArtContent from '@/components/main/ArtContent/ArtContent';
import api from '@/services/TokenService';
import { useState } from 'react';
import { UserTypes } from '@/constants/types/home';
import LoginAfterNavigationBar from '@/components/common/NavigationBar/LoginAfterNavigationBar';

const Home = () => {
  const [user, setUser] = useState(UserTypes.DEFAULT);
  const token = api.getToken();

  return (
    <div>
      <Head>
        <title>Objet</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {token ? <LoginAfterNavigationBar /> : <NavigationBar />}
      <MainBanner />
      <ArtContent />
    </div>
  );
};

export default Home;
